global class VSPR32_InvocableFitKitOrderRequest {
    @InvocableVariable(required=true)
    global String opportunityId;
    @InvocableVariable(required=true)
    global String Fitkit_Number;
    @InvocableVariable(required=true)
    global String Qty;
    @InvocableVariable(required=true)
    global String Name;
    @InvocableVariable(required=true)
    global String Street;
    @InvocableVariable(required=true)
    global String Country;
    @InvocableVariable(required=true)
    global String PostalCd;
    @InvocableVariable(required=true)
    global String City;
    @InvocableVariable(required=true)
    global String Region;
    @InvocableVariable(required=false)
    global String Telephone;
}